/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** 记忆检索结果 */
export interface MemoryHit {
  id: number
  score: number
  content: string
}
/** 内核状态 */
export interface KernelStatus {
  initialized: boolean
  version: string
}
/** Agent 内核 */
export declare class AgentKernel {
  /** 创建新的 Agent 内核 */
  constructor()
  /** 初始化内核 */
  initialize(): Promise<void>
  /** 发送消息 */
  chat(message: string): Promise<string>
  /** 执行工具 */
  executeTool(toolName: string, params: string): Promise<string>
  /** 搜索记忆 */
  searchMemory(query: string, k: number): Promise<Array<MemoryHit>>
  /** 获取内核状态 */
  getStatus(): KernelStatus
}
